vich_uploader:
  db_driver: orm

  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
  #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
  mappings:
    categories:
      uri_prefix: /images/categories
      upload_destination: "%kernel.project_dir%/public/images/categories"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    produits:
      uri_prefix: /images/produits
      upload_destination: "%kernel.project_dir%/public/images/produits"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
